services:
  job-seekr-app:
    image: ghcr.io/ivan-demchenko/job-seekr-app:latest
    environment:
      - DATABASE_URL=postgres://postgres:postgres@job-seekr-db:5432/postgres
      - HOSTING_MODE=local
      - ENV=prod
    depends_on:
      - job-seekr-db
      - job-seekr-db-setup
    ports:
      - "3000:3000"

  job-seekr-db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - job-seekr-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  job-seekr-db-setup:
    image: ghcr.io/ivan-demchenko/job-seekr-app:latest
    restart: "no"
    depends_on:
      - job-seekr-db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@job-seekr-db:5432/postgres
      - HOSTING_MODE=local
      - ENV=prod
    entrypoint: [ "bash", "-c", "bun run db:migration:run" ]

volumes:
  job-seekr-data:
