services:
  job-seekr-app:
    image: ghcr.io/ivan-demchenko/job-seekr-app:latest
    environment:
      - DATABASE_URL=postgres://postgres:postgres@job-seekr-db:5432/job-seekr
      - HOSTING_MODE=local
      - ENV=prod
    depends_on:
      - job-seekr-db
    command: sleep infinity
    ports:
      - "3000:3000"

  job-seekr-db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: job-seekr

volumes:
  postgres-data:
